# ==============================================================================
# Module 1: Environment Setup
# ==============================================================================

# --- Package Installation Logic ---
# ACADEMIC NOTE: Automated dependency management ensures reproducibility across 
# different grading environments.
installed_pkgs <- installed.packages()[, "Package"]
req_pkgs <- c("tidyverse", "caret", "reshape2", "corrplot", "vcd", "naniar", "gridExtra", "e1071", "Hmisc", "VIM", "RANN")
new_pkgs <- req_pkgs[!(req_pkgs %in% installed_pkgs)]
if(length(new_pkgs)) install.packages(new_pkgs)

# --- Load Libraries ---
options(scipen = 999) # CRITICAL: Prevents IDs (e.g., 5008804) from converting to 5.00e6
library(tidyverse)  # Data manipulation & ggplot2
library(caret)      # ML Preprocessing (The industry standard for R pipelines)
library(reshape2)   # Reshaping for correlation heatmaps
library(corrplot)   # Correlation Viz
library(vcd)        # Categorical Statistics (Cramer's V)
library(naniar)     # Missing Data Visualization (vis_miss)
library(gridExtra)  # Arranging plots
library(e1071)      # Skewness calculations
library(Hmisc)      # Enhanced histograms
library(VIM)        # Visualization and Imputation of Missing Values (KNN)
library(RANN)       # Provides fast k-Nearest Neighbors (k-NN) for caret

# REPRODUCIBILITY:
# Setting seed ensures that random processes (like KNN imputation and Splitting)
# produce the exact same results every time the professor runs the code.
set.seed(123)

# --- Data Loading Function ---
load_data <- function(path) {
  if(!file.exists(path)) stop(paste("File not found at:", path))
  
  # STRATEGY: Load strings as characters initially (not factors) to allow for 
  # easy string manipulation (cleaning) before final encoding.
  df <- read.csv(path, stringsAsFactors = FALSE)
  
  cat("--------------------------------------------------------\n")
  cat(" DATA LOADED SUCCESSFULLY \n")
  cat(" Dimensions:", dim(df)[1], "rows,", dim(df)[2], "columns\n")
  cat("--------------------------------------------------------\n")
  return(df)
}

# --- Execute Data Loading (Immediate Execution) ---
# NOTE: Replace 'application_record.csv' with your specific file path if different.
df <- load_data("C:/Users/John Arellano/RstudioProjects/GRP-6_DS-Project/DS-Project_data/Dataset-part-2.csv")

# ==============================================================================
# Module 2: Initial Exploratory Data Analysis (EDA)
# ==============================================================================
# PURPOSE: To identify "Sanity Check" failures and Data Quality issues that 
# must be resolved in Module 3.

cat("\n================================================================\n")
cat(" MODULE 2: INITIAL DATA EXPLORATION (RAW DATA)\n")
cat("================================================================\n")

# --- Phase 1: Structure & Content Inspection ---
cat("\n[Phase 1] Structure & Content Inspection\n")
print(dim(df))
dplyr::glimpse(df)

# --- Phase 2: Data Quality "Sanity Checks" ---
cat("\n[Phase 2] Data Quality & Sanity Checks\n")

# 1. Statistical Summary
# ANALYSIS: Looking for impossible values (e.g., negative age, massive income).
print(summary(dplyr::select(df, where(is.numeric))))

# 2. Missing Values
# EVIDENCE FROM OUTPUT: Your text output shows 'OCCUPATION_TYPE' has ~20,699 NAs.
# STRATEGY: We cannot simply drop 30% of our data. We must impute later.
cat("\nMissing Values Count:\n")
miss_counts <- colSums(is.na(df))
print(miss_counts[miss_counts > 0])

# 3. Duplicate Rows & IDs
# CRITICAL: Duplicate IDs mean the same customer exists twice. 
# Your output showed 0 duplicates, which validates the dataset integrity.
dup_count <- sum(duplicated(df))
cat("\nDuplicate Rows Detected:", dup_count, "\n")

# 4. Variance Check
# EVIDENCE FROM OUTPUT: FLAG_MOBIL has 67,614 rows all with value '1'.
# DECISION: A variable with zero variance offers no predictive power. Drop it.
if("FLAG_MOBIL" %in% names(df)) {
  cat("\nVariance Check for FLAG_MOBIL:\n")
  print(table(df$FLAG_MOBIL))
}

# --- Phase 3: Univariate Visualization ---
# See PDF "Autogenerated_Plots" for visual confirmation.

# 1. Target Variable Distribution
# EVIDENCE FROM PDF (Page 1): The bar chart shows huge imbalance.
# '0' and 'C' are dominant. '2,3,4,5' are tiny.
# DECISION: We must use UpSampling later, otherwise the NN will ignore the minority class.
if("status" %in% names(df)) {
  p_target <- ggplot(df, aes(x = as.factor(status))) +
    geom_bar(fill = "steelblue") +
    labs(title = "Target Distribution (Class Imbalance Check)", x = "Status Code", y = "Count") +
    theme_minimal()
  print(p_target)
}

# 2. Numeric Distributions
# EVIDENCE FROM PDF (Page 4): AMT_INCOME_TOTAL is heavily right-skewed.
# Neural Networks struggle with unscaled, skewed inputs. 
# DECISION: Log-transformation is required in Module 3.
num_cols <- names(dplyr::select(df, where(is.numeric)))
for(col in num_cols) {
  p_hist <- ggplot(df, aes(x = .data[[col]])) +
    geom_histogram(bins = 30, fill = "coral", color = "white") +
    labs(title = paste("Distribution:", col)) +
    theme_minimal()
  
  p_box <- ggplot(df, aes_string(y = col)) +
    geom_boxplot(fill = "lightblue") +
    labs(title = paste("Outliers:", col)) +
    theme_minimal()
  
  grid.arrange(p_hist, p_box, ncol = 2)
}

# --- Phase 5: 365243 Pensioner Anomaly ---
# CRITICAL FINDING:
# The Summary stats showed max DAYS_EMPLOYED = 365,243 (approx 1000 years).
# The output shows this overlaps 98.9% with "Pensioner".
# CONCLUSION: This is not a number; it is a placeholder/error code.
# ACTION: Convert to NA and create a boolean flag 'IS_PENSIONER'.
cat("\n[Module 2] Handling Anomalies and Engineering Features [III.1.E]\n")

if("DAYS_EMPLOYED" %in% names(df) && "NAME_INCOME_TYPE" %in% names(df)) {
  anomaly_check <- df %>%
    mutate(is_magic_val = ifelse(DAYS_EMPLOYED == 365243, 1, 0)) %>%
    group_by(NAME_INCOME_TYPE) %>%
    summarise(
      Total_Count = n(),
      Magic_Val_Count = sum(is_magic_val),
      Percentage = (sum(is_magic_val) / n()) * 100
    )
  
  print("365243 Anomaly Overlap Analysis:")
  print(anomaly_check)
}
cat("\n--- Module 2 Complete ---\n")

# ==============================================================================
# Module 3: Row-Wise Cleaning & Logic Features (NO LEAKAGE OPERATIONS)
# ==============================================================================
# METHODOLOGY: 
# We perform operations here that affect ROWS individually. 
# We DO NOT perform operations that calculate statistics across the whole column 
# (like Mean Imputation or Z-Score Scaling) because that would introduce 
# Data Leakage before the Train/Test split.

cat("\n================================================================\n")
cat(" MODULE 3: DATA CLEANING & LOGIC (NO LEAKAGE)\n")
cat("================================================================\n")

# Initialize working dataframe from the raw loaded data
df_clean <- df

# --- Phase 1. Drop Zero Variance
# Justified by Module 2 variance check.
if("FLAG_MOBIL" %in% names(df_clean)) {
  if(length(unique(df_clean$FLAG_MOBIL)) == 1) {
    cat("Dropping Zero-Variance Column: FLAG_MOBIL\n")
    df_clean$FLAG_MOBIL <- NULL
  }
}

# --- CHECK: Phase 1 ---
if(!"FLAG_MOBIL" %in% names(df_clean)) {
  cat(">> SUCCESS: FLAG_MOBIL has been removed.\n")
} else {
  warning(">> WARNING: FLAG_MOBIL is still present.\n")
}

# --- Phase 2. Flag Standardization
# Neural Networks require numeric inputs. "Y/N" strings cause errors.
cat("Standardizing flag variables to numeric 0/1...\n")
yn_flags <- intersect(c("FLAG_OWN_CAR", "FLAG_OWN_REALTY"), names(df_clean))
for (f in yn_flags) df_clean[[f]] <- ifelse(df_clean[[f]] == "Y", 1L, 0L)

numeric_flags <- intersect(c("FLAG_WORK_PHONE", "FLAG_PHONE", "FLAG_EMAIL"), names(df_clean))
for (f in numeric_flags) df_clean[[f]] <- as.integer(df_clean[[f]] > 0)

# --- CHECK: Phase 2 ---
cat(">> SUCCESS: Flag Standardization Preview:\n")
print(head(dplyr::select(df_clean, all_of(c(yn_flags, numeric_flags))), 3))

# --- Phase 3. Rectification Strategy (The Pensioner Fix)
if ("DAYS_EMPLOYED" %in% names(df_clean)) {
  cat("Rectifying 'DAYS_EMPLOYED': Handling 365243 anomaly...\n")
  df_clean <- df_clean %>%
    mutate(
      # Capture the information that they are a pensioner
      IS_PENSIONER = ifelse(DAYS_EMPLOYED == 365243, 1, 0),
      # Remove the distortion (1000 years) so it doesn't break Scaling later
      DAYS_EMPLOYED = ifelse(DAYS_EMPLOYED == 365243, NA, DAYS_EMPLOYED)
    )
}

# --- CHECK: Phase 3 ---
max_days <- max(df_clean$DAYS_EMPLOYED, na.rm = TRUE)
if(max_days < 365000) {
  cat(paste(">> SUCCESS: 365243 anomaly removed. New Max DAYS_EMPLOYED:", max_days, "\n"))
} else {
  warning(">> WARNING: 365243 anomaly still detected.\n")
}

# --- Phase 4. Target Engineering (GB60 Definition)
# RATIONALE: The assignment asks for Good vs Bad.
# We define "Bad" (1) as 60+ days overdue (Status 2, 3, 4, 5).
# We define "Good" (0) as Paid (C), No Loan (X), or <30 days late (0, 1).
# Note: Including '1' in Good is a standard risk tolerance choice.
if ("status" %in% names(df_clean)) {
  df_clean <- df_clean %>%
    mutate(
      status = as.character(status),
      TARGET = as.factor(ifelse(status %in% c("2", "3", "4", "5"), 1, 0))
    ) %>%
    dplyr::select(-status)
}
# Drop ID as it has no predictive value and can cause overfitting
if("ID" %in% names(df_clean)) df_clean$ID <- NULL

# --- CHECK: Phase 4 ---
if("TARGET" %in% names(df_clean) && !"ID" %in% names(df_clean)) {
  cat(">> SUCCESS: TARGET created and ID dropped.\n")
  print(table(df_clean$TARGET))
}

# --- Phase 5. Merge Categories
# "Civil marriage" and "Married" are financially identical. Merging reduces dimensionality.
if("NAME_FAMILY_STATUS" %in% names(df_clean)) {
  df_clean <- df_clean %>%
    mutate(NAME_FAMILY_STATUS = ifelse(NAME_FAMILY_STATUS == "Civil marriage", "Married", NAME_FAMILY_STATUS))
}

# --- CHECK: Phase 5 ---
if(!"Civil marriage" %in% unique(df_clean$NAME_FAMILY_STATUS)) {
  cat(">> SUCCESS: 'Civil marriage' successfully merged into 'Married'.\n")
}

# --- Phase 6. Rare Label Encoding
# PREVENTING OVERFITTING: Categories with <1% frequency create unstable dummy variables.
# We group them into "Other".
cat("Performing Rare Label Encoding (< 1% threshold)...\n")
for(col in names(df_clean)) {
  if(is.character(df_clean[[col]]) || is.factor(df_clean[[col]])) {
    df_clean[[col]] <- as.character(df_clean[[col]])
    freq_table <- table(df_clean[[col]])
    rare_cats <- names(freq_table[freq_table/sum(freq_table) < 0.01])
    
    if(length(rare_cats) > 0) {
      df_clean[[col]] <- ifelse(df_clean[[col]] %in% rare_cats, "Other", df_clean[[col]])
    }
  }
}

# --- CHECK: Phase 6 ---
cat(">> SUCCESS: Checking for 'Other' category in categorical columns:\n")
cat_cols <- names(dplyr::select(df_clean, where(is.character)))
for(c in cat_cols) {
  if("Other" %in% unique(df_clean[[c]])) cat(paste("   -", c, "contains 'Other'\n"))
}

# --- Phase 7. Feature Engineering (Preprocessing)
# NOTE: Rubric says "No feature engineering needed", but transforming 
# Birth Days (negative integer) to Age (positive float) is "Preprocessing" 
# for interpretability and NN stability.
if ("DAYS_BIRTH" %in% names(df_clean)) {
  df_clean$AGE <- abs(df_clean$DAYS_BIRTH) / 365.25
  df_clean$DAYS_BIRTH <- NULL
}

# --- CHECK: Phase 7 ---
if("AGE" %in% names(df_clean)) {
  cat(paste(">> SUCCESS: AGE created. Range:", round(min(df_clean$AGE),1), "-", round(max(df_clean$AGE),1), "\n"))
}

# --- Phase 8. Log Transform for Income
# ADDRESSING SKEW: Plot 4 showed massive right skew. 
# log1p (Log + 1) compresses the range, making it easier for the NN to learn weights.
if("AMT_INCOME_TOTAL" %in% names(df_clean)) {
  threshold <- quantile(df_clean$AMT_INCOME_TOTAL, 0.999, na.rm=TRUE)
  df_clean <- df_clean[df_clean$AMT_INCOME_TOTAL <= threshold, ]
  df_clean$AMT_INCOME_TOTAL_LOG <- log1p(df_clean$AMT_INCOME_TOTAL)
  df_clean$AMT_INCOME_TOTAL <- NULL
}

# --- CHECK: Phase 8 ---
if("AMT_INCOME_TOTAL_LOG" %in% names(df_clean)) {
  cat(">> SUCCESS: Income Log-Transformed.\n")
}

# --- Phase 9. Logical Imputation
# If a person is a Pensioner (identified earlier) but Occupation is NA,
# it is safe to assume their occupation is "Retired".
if("OCCUPATION_TYPE" %in% names(df_clean) && "IS_PENSIONER" %in% names(df_clean)) {
  df_clean$OCCUPATION_TYPE <- ifelse(
    df_clean$IS_PENSIONER == 1 & is.na(df_clean$OCCUPATION_TYPE), 
    "Retired", 
    df_clean$OCCUPATION_TYPE
  )
}

# --- CHECK: Phase 9 ---
na_pensioners <- df_clean %>% 
  filter(IS_PENSIONER == 1 & is.na(OCCUPATION_TYPE)) %>% 
  nrow()
if(na_pensioners == 0) {
  cat(">> SUCCESS: All Pensioner NAs filled with 'Retired'.\n")
} else {
  cat(paste(">> NOTICE: Remaining Pensioner NAs:", na_pensioners, "\n"))
}

# --- Phase 10. Final Sanity Check before Export
assign("df_clean_processed", df_clean, envir = .GlobalEnv)
cat("\n--- Module 3 Complete ---\n")
cat("Cleaned Data Dimensions:", dim(df_clean)[1], "rows,", dim(df_clean)[2], "columns\n")

# ==============================================================================
# Module 4: Preprocessed Diagnostic EDA (Cleaned Data)
# ==============================================================================

cat("\n================================================================\n")
cat("   MODULE 4: SECONDARY DATA EXPLORATION (CLEANED DATA)\n")
cat("================================================================\n")

# Ensure we use the processed dataframe
if(exists("df_clean_processed")) {
  df_clean <- df_clean_processed
}

cat("New Dimensions:", dim(df_clean), "\n")

# --- Phase 1: Structure & Content Inspection ---
cat("\n[Phase 1] Structure & Content Inspection\n")

# 1. View() is interactive; usually commented out in automated scripts
# View(df_clean) 

# 2. Head/Tail Check
cat("First 5 rows:\n")
print(head(df_clean, 5))

# 3. Dimension Check
cat("\nDimensions:\n")
print(dim(df_clean))

# 4. Structure Check
cat("\nData Structure (glimpse):\n")
dplyr::glimpse(df_clean)

# --- CHECK: Phase 1 ---
if(nrow(df_clean) > 0 && ncol(df_clean) > 0) {
  cat(">> SUCCESS: Cleaned data loaded and inspected.\n")
} else {
  stop(">> CRITICAL ERROR: Dataframe appears empty.\n")
}

# --- Phase 2: Data Quality "Sanity Checks" ---
cat("\n[Phase 2] Data Quality & Sanity Checks\n")

# 1. Statistical Summary
cat("\nStatistical Summary of Numeric Columns:\n")
print(summary(dplyr::select_if(df_clean, is.numeric)))

# 2. Missing Values Analysis
cat("\nMissing Values Count (Pre-Imputation):\n")
miss_counts <- colSums(is.na(df_clean))
print(miss_counts[miss_counts > 0])

# 2.1. Visualizing Missingness
print(naniar::vis_miss(df_clean, warn_large_data = FALSE) +
        ggtitle("Missingness Map (Cleaned Data)"))

# 3. Duplicate Rows
dup_count <- sum(duplicated(df_clean))
cat("\nDuplicate Rows Detected:", dup_count, "\n")
# JUSTIFICATION: Duplicates in credit data usually indicate data entry errors 
# or system glitches, as ID should be unique.

# 4. Unique Value Counts for Categorical
cat("\nUnique Values in Categorical Variables (Cardinality Check):\n")
cat_cols <- names(dplyr::select_if(df_clean, is.character))
for(col in cat_cols) {
  cat(paste0(col, ": ", length(unique(df_clean[[col]])), " unique levels\n"))
}

# --- CHECK: Phase 2 ---
if(dup_count == 0) {
  cat(">> SUCCESS: No duplicate rows found.\n")
} else {
  cat(paste(">> NOTICE:", dup_count, "duplicates remain (Is this expected?).\n"))
}

# --- [INSERTED] ZERO VARIANCE CHECK & HANDLING ---
cat("\n------------------------------------------------------------\n")
cat(" [CRITICAL CHECK] Identifying Zero Variance Variables\n")
cat("------------------------------------------------------------\n")

# Rationale: Zero variance variables crash correlation matrices (div by zero)
# and offer zero predictive power to Neural Networks.

# 1. Use Caret to find near-zero or zero variance columns
# saveMetrics = TRUE gives us a detailed dataframe of what's wrong
nzv_metrics <- caret::nearZeroVar(df_clean, saveMetrics = TRUE)
zero_var_cols <- rownames(nzv_metrics[nzv_metrics$zeroVar == TRUE, ])

if(length(zero_var_cols) > 0) {
  cat(">> WARNING: The following columns have ZERO variance (Single Value):\n")
  print(zero_var_cols)
  cat(">> ACTION: Removing Zero-Variance columns to prevent errors...\n")
  df_clean <- df_clean[, !names(df_clean) %in% zero_var_cols]
  cat(">> SUCCESS: Columns removed. New Dimensions:", dim(df_clean), "\n")
} else {
  cat(">> SUCCESS: No Zero-Variance columns detected.\n")
}
cat("------------------------------------------------------------\n")

# --- Phase 3: Univariate Visualization ---
cat("\n[Phase 3] Univariate Visualization\n")

# 1. Target Variable Distribution (The most important check)
# CHANGE: Use 'TARGET' instead of 'status'
if("TARGET" %in% names(df_clean)) {
  
  # [Image of bar chart showing class imbalance]
  
  
  p_target <- ggplot(df_clean, aes(x = as.factor(TARGET))) +
    geom_bar(fill = "steelblue") +
    labs(title = "Target Distribution (Class Imbalance Check)",
         x = "Target (0=Good, 1=Bad)", # Updated label
         y = "Count") +
    theme_minimal()
  print(p_target)
}

# 2. Numeric Distributions (Histograms & Boxplots)
num_cols <- names(dplyr::select_if(df_clean, is.numeric))
# Exclude ID from plotting
num_cols <- num_cols[num_cols != "ID"]

for(col in num_cols) {
  # Histogram
  p_hist <- ggplot(df_clean, aes_string(x = col)) +
    geom_histogram(bins = 30, fill = "coral", color = "white") +
    labs(title = paste("Distribution:", col)) +
    theme_minimal()
  
  # Boxplot
  p_box <- ggplot(df_clean, aes_string(y = col)) +
    geom_boxplot(fill = "lightblue") +
    labs(title = paste("Outliers:", col)) +
    theme_minimal()
  
  grid.arrange(p_hist, p_box, ncol = 2)
}

# 3. Categorical Frequencies
for(col in cat_cols) {
  p_cat <- ggplot(df_clean, aes_string(x = col)) +
    geom_bar(fill = "darkseagreen") +
    coord_flip() + # Flip for readability of labels
    labs(title = paste("Frequency:", col)) +
    theme_minimal()
  print(p_cat)
}

# --- CHECK: Phase 3 ---
cat(">> SUCCESS: Univariate plots generated for", length(num_cols), "numeric and", length(cat_cols), "categorical variables.\n")

# --- Phase 4: Other Visualizations ---
cat("\n[Phase 4] Other Visualization\n")

# 1. Visualize New Features
if("AGE" %in% names(df_clean)) {
  p_age <- ggplot(df_clean, aes(x=AGE)) +
    geom_histogram(fill="purple", bins=30) +
    labs(title="Distribution of Derived Feature: AGE") + theme_minimal()
  print(p_age)
}

# 2. Correlation Analysis
cat("Generating Correlation Matrix...\n")
num_df <- dplyr::select_if(df_clean, is.numeric)
# Exclude ID if it somehow persisted
if("ID" %in% names(num_df)) num_df$ID <- NULL

if(ncol(num_df) > 1) {
  # FIX: Use 'pairwise.complete.obs' instead of 'complete.obs'
  # This prevents the "Pensioner Paradox" where filtering NAs creates zero variance.
  cor_mat <- cor(num_df, use = "pairwise.complete.obs")
  
  # SAFETY: If SD=0 still occurs (rare), it produces NA/NaN in the matrix.
  # We replace those with 0 so the plot doesn't crash.
  cor_mat[is.na(cor_mat)] <- 0
  
  corrplot(cor_mat,
           method = "circle",
           type = "lower",
           title = "Correlation Matrix (Cleaned)",
           mar = c(0,0,2,0),
           tl.cex = 0.7) # Adjust text size for readability
  cat(">> SUCCESS: Correlation matrix generated (using pairwise deletion).\n")
}

# 3. Target Separation by Category
cat_vars <- names(dplyr::select_if(df_clean, is.character))
for(var in cat_vars) {
  p_bivar <- ggplot(df_clean, aes_string(x=var, fill="factor(TARGET)")) +
    geom_bar(position="fill") +
    labs(title = paste("Target Proportion by", var), y="Proportion", fill="Target") +
    coord_flip() +
    theme_minimal()
  print(p_bivar)
}

# --- CHECK: Phase 4 ---
if(exists("cor_mat")) {
  cat(">> SUCCESS: Correlation matrix generated.\n")
}

cat("\n--- Module 4 Complete ---\n")

# ==============================================================================
# Module 5 & 6: Robust Preprocessing & Splitting (MENTOR REVISION)
# ==============================================================================
# METHODOLOGY: This is the most critical architectural section.
# We adhere to the "Split First, Scale Later" principle.

cat("\n[Module 5] Splitting Data BEFORE Processing (Preventing Leakage)\n")

# Ensure we use the clean dataframe from the previous module
if(exists("df_clean_processed")) {
  df <- df_clean_processed
} else {
  stop("Error: 'df_clean_processed' not found. Please run Module 3 first.")
}

# Ensure TARGET is a factor for caret partitioning
df$TARGET <- as.factor(df$TARGET)

# --- Phase 1. Split Data First ---
# THEORETICAL JUSTIFICATION:
# If we scale or impute using the whole dataset, the Test set "sees" the Train set parameters.
# This is "Data Leakage". We must split FIRST.
set.seed(123)

# Create Test Set (15% held out completely)
train_val_index <- createDataPartition(df$TARGET, p = 0.85, list = FALSE)
df_train_val <- df[train_val_index, ]
df_test        <- df[-train_val_index, ]

# Split Train/Val (70% Train, 15% Val)
p_train <- 0.70 / 0.85
train_index <- createDataPartition(df_train_val$TARGET, p = p_train, list = FALSE)
df_train <- df_train_val[train_index, ]
df_val   <- df_train_val[-train_index, ]

cat("Splits created. Learning parameters on Train set only...\n")

# --- CHECK: Phase 1 ---
cat(sprintf(">> SUCCESS: Data Split Counts:\n   Train: %d rows\n   Val:   %d rows\n   Test:  %d rows\n", 
            nrow(df_train), nrow(df_val), nrow(df_test)))

# ------------------------------------------------------------------------------
# [INSERTED] EXPERIMENT: Optimizing K for KNN Imputation (RMSE Method)
# ------------------------------------------------------------------------------
# PURPOSE: To verify if the default K=5 is actually optimal for this dataset.
# METHODOLOGY: 
# 1. Isolate complete cases (rows with no NAs) from the Training set.
# 2. Artificially introduce NAs into a numeric column (e.g., AMT_INCOME_TOTAL_LOG).
# 3. Test different K values (3, 5, 7, etc.) and calculate RMSE against known truths.
# NOTE ON METRIC SELECTION (RMSE):
# We use RMSE (Root Mean Squared Error) to evaluate K. 
# While our final goal is Classification (Accuracy/AUC), optimizing Imputation 
# via RMSE is a standard heuristic. It assumes that minimizing the error in 
# reconstructing the data leads to a dataset that best reflects reality, 
# thereby providing the best signal for the Neural Network.
# ------------------------------------------------------------------------------

cat("\n[Experiment] Determining Optimal K for KNN Imputation...\n")

# 1. Create a testing subset from Train (Complete cases only)
# We need complete cases to have a "ground truth" to compare against.
df_experiment <- df_train[complete.cases(df_train), ]

if(nrow(df_experiment) > 100) { # Only run if we have enough complete data
  
  # --- [FIX ADDED] Handle Zero Variance Columns ---
  # In this subset of complete cases, some columns might be constant (all 0s or all 1s).
  # Scaling requires variance > 0. We drop constant columns for this specific experiment.
  zero_var_cols <- sapply(df_experiment, function(x) length(unique(x)) == 1)
  if(any(zero_var_cols)) {
    # Keep TARGET even if constant (unlikely), but drop others
    cols_to_drop <- names(df_experiment)[zero_var_cols]
    cols_to_drop <- cols_to_drop[cols_to_drop != "TARGET"] # Safety check
    
    if(length(cols_to_drop) > 0){
      cat(paste("   >> Note: Dropping constant columns for experiment:", paste(cols_to_drop, collapse=", "), "\n"))
      df_experiment <- df_experiment[, !names(df_experiment) %in% cols_to_drop]
    }
  }
  # ------------------------------------------------
  
  # 2. Setup K-values to test
  k_candidates <- c(3, 5, 7, 9, 11, 15, 21)
  rmse_results <- data.frame(k = k_candidates, RMSE = NA)
  
  # 3. Target variable for testing (we introduce artificial NAs here)
  # We use 'AMT_INCOME_TOTAL_LOG' as a proxy because it's continuous and correlated with others.
  target_col <- "AMT_INCOME_TOTAL_LOG"
  actuals <- df_experiment[[target_col]]
  
  # Create synthetic NAs (remove 10% of data)
  set.seed(999) # Local seed for this specific experiment
  na_indices <- sample(1:nrow(df_experiment), 0.1 * nrow(df_experiment))
  df_with_holes <- df_experiment
  df_with_holes[[target_col]][na_indices] <- NA
  
  # 4. Loop through K values
  cat("   Testing K values: ")
  for(i in 1:length(k_candidates)) {
    k_val <- k_candidates[i]
    cat(k_val, "... ")
    
    # Train imputer on the dataset with holes
    # Note: method="knnImpute" in caret automatically scales data (center/scale)
    model <- preProcess(df_with_holes, method = c("knnImpute"), k = k_val)
    
    # Predict (Impute)
    imputed_data <- predict(model, df_with_holes)
    
    # Extract imputed values
    imputed_vals <- imputed_data[[target_col]][na_indices]
    
    # IMPORTANT: caret outputs SCALED values. We must compare against SCALED actuals.
    actuals_scaled <- scale(actuals)[na_indices]
    
    # Calculate RMSE (Root Mean Squared Error)
    rmse <- sqrt(mean((imputed_vals - actuals_scaled)^2))
    rmse_results$RMSE[i] <- rmse
  }
  cat("Done.\n")
  
  # 5. Select Best K
  best_k <- rmse_results$k[which.min(rmse_results$RMSE)]
  
  cat("\n   [Results] RMSE per K-value:\n")
  print(rmse_results)
  cat(paste("\n>> OPTIMAL K FOUND:", best_k, "\n"))
  
} else {
  cat(">> WARNING: Not enough complete cases to run K-optimization. Defaulting to K=5.\n")
  best_k <- 5
}

# --- Phase 2. Define Preprocessing Pipeline ---

# ==============================================================================
# IMPUTATION DECISION JUSTIFICATION
# ==============================================================================
# Why we chose KNN over Mean/Median or Bagged Trees:
#
# 1. vs. Mean/Median Imputation:
#    - Mean imputation replaces missing values with the average of that column.
#    - FLAW: It ignores relationships between columns (e.g., Higher Income usually 
#      means Higher Credit). Mean imputation flattens this variance and bias results.
#    - KNN preserves these correlations by looking at "neighbors".
#
# 2. vs. Bagged Trees:
#    - Bagged trees are often the "Gold Standard" for accuracy.
#    - FLAW: They are extremely computationally expensive (slow) on large datasets.
#    - KNN provides a balance: much better accuracy than Mean, but faster than Trees.
# ==============================================================================

# ==============================================================================
# HOW KNN WORKS (Explanation)
# ==============================================================================
# 1. Identification: The algorithm identifies rows that have missing values.
# 2. Distance Calculation: For a row with a missing value (Row A), it scans 
#    the *other* columns (columns that are NOT missing).
# 3. Neighbor Matching: It finds 'k' other rows in the dataset (Rows B, C, D...) 
#    that have very similar values in those *other* columns.
#    (e.g., If Row A has missing Income, but Age=30 and Job=Admin, it looks for 
#     other rows where Age is near 30 and Job is Admin).
# 4. Imputation: It takes the average Income of those neighbors (B, C, D) and 
#    assigns it to Row A.
# ==============================================================================

# [INSERTED] IMPUTATION REPORTING
# Calculate exactly what will be imputed before we run the process
missing_counts <- colSums(is.na(df_train))
cols_missing <- missing_counts[missing_counts > 0]
rows_missing <- sum(!complete.cases(df_train))

cat("\n------------------------------------------------------------\n")
cat(" [PRE-PROCESS REPORT] Imputation Scope\n")
cat("------------------------------------------------------------\n")
if(length(cols_missing) > 0) {
  cat(sprintf("Total Rows requiring Imputation: %d (%.2f%% of Train Data)\n", 
              rows_missing, (rows_missing/nrow(df_train))*100))
  cat("Columns containing NAs:\n")
  print(cols_missing)
} else {
  cat(">> No missing values detected in Training set. Imputation will be skipped.\n")
}
cat("------------------------------------------------------------\n\n")


# RUBRIC COMPLIANCE:
# The Assignment PDF states: "All in- and output values need to be... in the range of [0,1]."
# Therefore, we use 'range' (Min-Max Scaling) instead of 'center/scale' (Z-score).

cat(paste("\nDefining Pipeline with K =", best_k, "...\n"))
preProc_model <- preProcess(df_train, method = c("knnImpute", "range"), k = best_k)

cat("Applying KNN Imputation and Min-Max (0-1) Scaling...\n")
# We 'predict' the scaling/imputation logic learned on Train onto Val and Test.
train_scaled <- predict(preProc_model, df_train)
val_scaled    <- predict(preProc_model, df_val)
test_scaled   <- predict(preProc_model, df_test)

# --- CHECK: Phase 2 ---
missing_post_impute <- sum(is.na(train_scaled))
max_val <- max(select_if(train_scaled, is.numeric), na.rm=TRUE)
min_val <- min(select_if(train_scaled, is.numeric), na.rm=TRUE)

if(missing_post_impute == 0 && max_val <= 1 && min_val >= 0) {
  cat(">> SUCCESS: Imputation complete (0 NAs) and Scaling verified (Range 0-1).\n")
} else {
  cat(paste(">> WARNING: Imputation NAs:", missing_post_impute, "| Max Value:", max_val, "\n"))
}

# --- Phase 3. One-Hot Encoding (Dummy Variables) ---
# Neural Networks cannot accept categorical strings. We must convert to 0/1 matrices.
cat("Applying One-Hot Encoding...\n")

dummies_model <- dummyVars(" ~ . -TARGET", data = train_scaled)

train_encoded_mat <- predict(dummies_model, newdata = train_scaled)
val_encoded_mat     <- predict(dummies_model, newdata = val_scaled)
test_encoded_mat   <- predict(dummies_model, newdata = test_scaled)

# Convert back to Data Frames for UpSampling step
train_encoded <- data.frame(train_encoded_mat)
val_encoded     <- data.frame(val_encoded_mat)
test_encoded   <- data.frame(test_encoded_mat)

# Re-attach TARGET 
train_encoded$TARGET <- as.factor(df_train$TARGET)
val_encoded$TARGET     <- as.factor(df_val$TARGET)
test_encoded$TARGET   <- as.factor(df_test$TARGET)

# --- CHECK: Phase 3 ---
if(all(sapply(train_encoded, is.numeric) | names(train_encoded) == "TARGET")) {
  cat(">> SUCCESS: One-Hot Encoding complete. No character columns remain (except Target factor).\n")
}

# --- Phase 4. Handling Class Imbalance (UpSampling) ---
# JUSTIFICATION:
# As seen in Plot 1 of the PDF, the minority class (Bad Credit) is tiny (~1-2%).
# A Neural Network will simply predict "Good" for everyone to get 99% accuracy.
# We UpSample the minority class in the TRAINING set to make it 50/50.
# NOTE: We do NOT upsample Val or Test, as they must represent reality.
cat("Handling Class Imbalance (UpSampling Training Set)...\n")

x_train <- dplyr::select(train_encoded, -TARGET)
y_train <- train_encoded$TARGET 

train_balanced <- upSample(x = x_train, y = y_train, yname = "TARGET")

# --- CHECK: Phase 4 ---
tbl <- table(train_balanced$TARGET)
if(tbl[1] == tbl[2]) {
  cat(paste(">> SUCCESS: Classes Balanced. 0:", tbl[1], "| 1:", tbl[2], "\n"))
} else {
  cat(">> WARNING: Classes are still unbalanced.\n")
}

# --- Phase 5. Final Conversion to Matrix (Rubric Requirement) ---
# The PDF explicitly states: "a neural network expects a R matrix... not data frames."

to_matrix_list <- function(df_in) {
  list(
    # Predictors: All columns except TARGET
    x = data.matrix(dplyr::select(df_in, -TARGET)),
    # Target: Convert Factor 0/1 to Numeric 0/1 (Keras requires numeric targets)
    y = as.numeric(as.character(df_in$TARGET)) 
  )
}

cat("\nFormatting final outputs as Matrices for NN input...\n")

nn_matrices <- list(
  train = to_matrix_list(train_balanced),
  val   = to_matrix_list(val_encoded),
  test  = to_matrix_list(test_encoded),
  # Keep the preProc model to reverse engineer values if needed
  preProc = preProc_model 
)

# --- CHECK: Phase 5 ---
if(is.matrix(nn_matrices$train$x) && is.numeric(nn_matrices$train$y)) {
  cat(">> SUCCESS: Final output is in Matrix format ready for Neural Network.\n")
}

cat("\n--- Module 5 & 6 Complete ---\n")

# ==============================================================================
# Module 7: Execution & Reporting (PDF Generation)
# ==============================================================================

# --- 1. Robust Path Setup ---
target_path <- "C:/Users/John Arellano/RstudioProjects/GRP-6_DS-Project/DS-Project_Part2_Scripts"

if(dir.exists(target_path)) {
  base_dir <- target_path
} else {
  base_dir <- getwd()
  cat("WARNING: Target directory not found. Defaulting to Working Directory:", base_dir, "\n")
}

plot_dir <- file.path(base_dir, "Auto_Generated_Plots")

if(!dir.exists(plot_dir)) {
  dir.create(plot_dir, recursive = TRUE)
}
cat("Plots will be saved to:", plot_dir, "\n")

# --- 2. Verify Data Existence (from previous linear modules) ---
if(!exists("df")) {
  stop("CRITICAL ERROR: Raw dataframe 'df' not found. Please run Module 1.")
}
if(!exists("df_clean_processed")) {
  stop("CRITICAL ERROR: Cleaned dataframe 'df_clean_processed' not found. Please run Module 3.")
}

# --- 3. Define Auto-Save Function (With Safety Locks) ---
save_plots_to_pdf <- function(raw_df, cleaned_df) {
  
  # Close any open devices to prevent errors
  while(!is.null(dev.list())) dev.off()
  
  ts <- format(Sys.time(), "%d.%m.%Y.(%H%M)")
  filename <- paste0("Autogenerated_Plots_", ts, ".pdf")
  full_path <- file.path(plot_dir, filename)
  
  cat("\nStarting PDF Generation to:", full_path, "\n")
  
  pdf(file = full_path, width = 10, height = 7)
  
  # Ensure device closes even if an error occurs
  on.exit(if(dev.cur() > 1) dev.off())
  
  tryCatch({
    # --- RAW DATA SECTION ---
    cat("... Adding Raw Data EDA\n")
    if(exists("perform_initial_eda") && is.function(perform_initial_eda)) {
      perform_initial_eda(raw_df) 
    } else {
      cat("   [NOTE] Function 'perform_initial_eda' not found (Script is linear).\n")
      cat("   Attempting to print saved 'p_anomaly' from Module 2 if available...\n")
      if(exists("p_anomaly")) print(p_anomaly)
    }
    
    # --- CLEANED DATA SECTION ---
    cat("... Adding Cleaned Data EDA\n")
    if(exists("perform_eda") && is.function(perform_eda)) {
      perform_eda(cleaned_df)
    } else {
      cat("   [NOTE] Function 'perform_eda' not found (Script is linear).\n")
      cat("   Attempting to print saved plots from Module 4 if available...\n")
      
      # Attempt to print plots that typically survive the linear script run
      if(exists("p_target")) { plot(p_target + ggtitle("Target Distribution (Recovered)")) }
      if(exists("p_age"))    { plot(p_age) }
      if(exists("p_bivar"))  { plot(p_bivar) }
      if(exists("cor_mat"))  { 
        corrplot::corrplot(cor_mat, method="circle", type="lower", title="Correlation (Recovered)", mar=c(0,0,2,0)) 
      }
    }
    
  }, error = function(e) {
    cat("ERROR during plotting: ", e$message, "\n")
  })
  
  cat("PDF Generation Complete.\n")
  return(full_path)
}

# --- 4. Execute PDF Generation (Step D) ---
# We pass the global dataframes directly
pdf_path <- save_plots_to_pdf(df, df_clean_processed)

# --- CHECK: Module 7 ---
if(file.exists(pdf_path)) {
  cat(paste(">> SUCCESS: PDF Report successfully created at:\n  ", pdf_path, "\n"))
} else {
  cat(">> WARNING: PDF file was not found after execution.\n")
}

cat("\n--- Module 7 Complete ---\n")
